name: artist_replugged
description: A new Flutter project.


publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: ">=2.17.0-266.5.beta <3.0.0"


dependencies:
  flutter:
    sdk: flutter



  cupertino_icons: ^1.0.4
  webview_flutter: ^3.0.4 
  flutter_phoenix: ^1.0.0
  video_player: ^2.4.0
  google_fonts:
  flutter_hooks: ^0.18.3
 
  carousel_slider: ^4.1.1

  kiwi: ^4.0.2
  dartz: ^0.10.1
  bloc: ^7.0.0
  flutter_bloc: ^7.0.1
  shared_preferences: ^2.0.15
  json_serializable: ^6.2.0
  
  firebase_auth:
  firebase_messaging: ^11.2.4
 
  share_plus: ^4.0.10
  cached_network_image: ^3.2.1
  
  url_launcher: 
  flutter_to_airplay: ^2.0.2
 
  native_device_orientation: ^1.1.4 
  youtube_player_iframe: ^3.1.0
  flutter_local_notifications: ^9.1.4
  avatar_glow: ^2.0.2
  
  audio_video_progress_bar: ^0.11.0
  video_360: ^0.0.8
  assistive_touch: ^0.2.0
  uni_links: ^0.5.1
  path_provider: ^2.0.11
  firebase_core: ^1.10.4
 
 


  
  
 



  
 
 





 

  
  

  
  

  
 
  

dev_dependencies:
  build_runner: ^2.1.11
 
  freezed: ^2.0.3
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.1

flutter:

  uses-material-design: true

  assets:
    - assets/images/
    - assets/icons/